In [3]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (3.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/riya/Library/Python/3.11/lib/python/site-packages (from pandas) (1.24.3)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [4]:
import pandas as pd 

path = "/Users/riya/Documents/pfas/data/landfills.xlsx"

landfilldf = pd.read_excel(path, sheet_name = 'LMOP Database')
landfilldf=landfilldf.drop_duplicates(subset='Landfill ID')

In [5]:
selected_columns = landfilldf[['Latitude', 'Longitude', 'Landfill ID', 'Current Landfill Status', 'Waste in Place (tons)', 'Ownership Type', 
                              'Current Project Status', 'LFG Collected (mmscfd)']]

selected_columns.head()

,Latitude,Longitude,Landfill ID,Current Landfill Status,Waste in Place (tons),Ownership Type,Current Project Status,LFG Collected (mmscfd)
0,41.707000,-70.895000,1833,Closed,900000.0,Public,Low Potential,NaN
1,42.371200,-72.510800,789,Closed,525096.0,Public,Low Potential,NaN
2,41.940000,-71.235000,794,Closed,1000000.0,Private,Shutdown,0.72
5,41.661100,-70.391100,2334,Closed,2000000.0,Public,Low Potential,NaN
6,42.092537,-72.594646,793,Closed,NaN,Public,Shutdown,0.36

In [6]:
print(landfilldf)

     GHGRP ID  Landfill ID                          Landfill Name State  \
0         NaN         1833                            Acushnet LF    MA
1         NaN          789                             Amherst LF    MA
2         NaN          794       Attleboro Landfill, Incorporated    MA
5         NaN         2334                          Barnstable LF    MA
6   1007948.0          793                  Bondi Island Landfill    MA
7   1004958.0          774                              Bourne LF    MA
8         NaN         1834                           Braintree LF    MA
9   1005715.0        20851         Carver-Marion-Wareham Landfill    MA
10        NaN          795                             Chatham LF    MA
11        NaN          796           Chicopee Landfill (Republic)    MA
12  1007669.0          775                Chicopee Landfill (WMI)    MA
13  1005039.0          788                          Crapo Hill LF    MA
14        NaN        21260                       Danvers Landfill    MA
15        NaN          776                           Dartmouth LF    MA
16  1004556.0          777                    East Bridgewater LF    MA
18  1007547.0          778                    Fall River Landfill    MA
21  1007753.0          787               Fitchburg-Westminster LF    MA
25  1005466.0        20855                Gardner Street Landfill    MA
26        NaN          784                                 GCR LF    MA
27  1007685.0          779                             Granby SLF    MA
28        NaN          802                    Greenwood Street LF    MA
29  1007550.0          797                             Halifax LF    MA
30  1005379.0        20897                      Hardwick Landfill    MA
31  1005213.0        10660                     Haverhill Landfill    MA
32        NaN        21199                          Hull Landfill    MA
33        NaN          798                           Leicester LF    MA
34        NaN          801                              Lowell LF    MA
36        NaN          799                              Marion LF    MA
37        NaN          781                          Marshfield LF    MA
38  1003587.0          773                       Martone Landfill    MA
39  1010391.0        20703                 Middleborough Landfill    MA
40        NaN          790                           Nantucket LF    MA
41        NaN          791                         New Bedford LF    MA
42  1002593.0         1835                   Northampton Landfill    MA
43        NaN          803                 Otis Air Force Base LF    MA
44        NaN          783                              Palmer LF    MA
45  1004557.0          785                          Plainville LF    MA
47        NaN        10641                  Quarry Hills Soils LF    MA
50  1007947.0          792                            Randolph LF    MA
51        NaN          780                     RCI Hudson/Stow LF    MA
52        NaN         1836                       Shaffer Landfill    MA
53  1004157.0         2301              South Hadley Landfill LLC    MA
54        NaN          800                   South Meadow Road LF    MA
55  1005254.0        10100  Southbridge Recycling & Disposal Park    MA
56        NaN        21141                    Sturbridge Landfill    MA
57  1003532.0          786                            Taunton SLF    MA
59        NaN        10362                             Wayland LF    MA
60  1003393.0        10780                   West Street Landfill    MA
61        NaN         2197                     Westfield Landfill    MA
62        NaN         1951                    Winchendon Landfill    MA

                    Physical Address              City      County  Zip Code  \
0                    561 Main Street          Acushnet     Bristol      2743
1               740 Belchertown Road           Amherst   Hampshire      1002
2                 179 Peckham Street         Attleboro     Bristol      2703
5                    45 Flint Street    Marstons Mills  Barnstable      2648
6                      Agawam Avenue  West Springfield     Hampden      1089
7   201 MacArthur Boulevard Route 28            Bourne  Barnstable      2532
8        Union Street & Ivory Street         Braintree     Norfolk      2184
9                   118 Federal Road            Carver    Plymouth      2330
10                 92 Sam Ryder Road           Chatham  Barnstable      2633
11                  845 Burnett Road          Chicopee     Hampden      1020
12              161 New Lombard Road          Chicopee     Hampden      1020
13       300 Samuel Barnet Boulevard       New Bedford     Bristol      2745
14       East Coast Road\nPopes Lane           Danvers       Essex      1923
15           976 Russells Mills Road         Dartmouth    Plymouth      2748
16               234 Thatcher Street  East Bridgewater    Plymouth      2333
18                 1080 Airport Road        Fall River     Bristol      2720
21                101 Fitchburg Road       Westminster   Worcester      1473
25      Gardner Street, West Roxbury            Boston     Suffolk      2201
26               Farm Avenue Route 1           Peabody       Essex      1960
27                11 New Ludlow Road            Granby   Hampshire      1033
28                 30 Nippnapp Trail         Worcester   Worcester      1607
29                  27 Laurel Street           Halifax    Plymouth      2338
30          1270 Patrill Hollow Road          Hardwick   Hampshire      1037
31                  100 Recovery Way         Haverhill       Essex      1835
32                      Logan Avenue              Hull    Plymouth      2045
33              151 Mannville Street         Leicester   Worcester      1524
34              1290 Westford Street            Lowell   Middlesex      1851
36                 Benson Brook Road            Marion    Plymouth      2738
37      Clay Pit Road & Grove Street        Marshfield    Plymouth      2050
38               99 Barre Depot Road             Barre   Worcester      1005
39               207 Plympton Street     Middleborough    Plymouth      2346
40                  188 Madaket Road         Nantucket   Nantucket      2554
41               1103 Shawmut Avenue       New Bedford     Bristol      2746
42                 170 Glendale Road          Florence   Hampshire      1062
43                      Connery Road      Buzzards Bay  Barnstable      2532
44                      Emery Street            Palmer     Hampden      1069
45                 14 Belcher Street        Plainville     Norfolk      2762
47                    Ricciuti Drive            Quincy     Norfolk      2169
50                     Johnson Drive          Randolph     Norfolk      2368
51                     Old Stow Road            Hudson   Middlesex      1749
52                               NaN         Billerica   Middlesex      1821
53               12 Industrial Drive      South Hadley   Hampshire      1075
54                 South Meadow Road           Clinton   Middlesex      1510
55                 165 Barefoot Road       Southbridge   Worcester      1550
56                154 Breakneck Road        Sturbridge   Worcester      1556
57         340 East Britannia Street           Taunton     Bristol      2780
59              484 Boston Post Road           Wayland   Middlesex      1778
60                   744 West Street           Gardner   Worcester      1440
61                      Twiss Street         Westfield     Hampden      1085
62                  202 River Street        Winchendon   Worcester      1475

     Latitude  Longitude  ... Project Start Date Project Shutdown Date  \
0   41.707000 -70.895000  ...                NaT                   NaT
1   42.371200 -72.510800  ...                NaT                   NaT
2   41.940000 -71.235000  ...         1997-11-01            2004-12-31
5   41.661100 -70.391100  ...                NaT                   NaT
6   42.092537 -72.594646  ...         1994-01-01            2004-01-01
7   41.728000 -70.581300  ...                NaT                   NaT
8   42.207276 -70.997994  ...         1999-10-01            1999-11-01
9   41.812833 -70.719500  ...                NaT                   NaT
10  41.686600 -70.006200  ...                NaT                   NaT
11  42.175200 -72.532500  ...         1993-07-01            2008-01-01
12  42.165900 -72.538000  ...         2004-02-21                   NaT
13  41.725000 -70.982000  ...         2005-11-01                   NaT
14  42.559618 -70.987311  ...                NaT                   NaT
15  41.579800 -71.000200  ...                NaT                   NaT
16  42.063420 -70.978570  ...         1997-02-01            2010-12-01
18  41.751000 -71.106800  ...         2000-07-01                   NaT
21  42.535960 -71.853880  ...         2007-08-01                   NaT
25  42.282000 -71.182000  ...                NaT                   NaT
26  42.527000 -70.986800  ...                NaT                   NaT
27  42.221400 -72.545900  ...         2001-10-15                   NaT
28  42.218739 -71.789885  ...                NaT                   NaT
29  41.991800 -70.899200  ...         1997-04-01            2010-06-30
30  42.335000 -72.237200  ...                NaT                   NaT
31  42.764640 -71.125040  ...         2008-01-01            2018-12-31
32  42.261836 -70.857348  ...                NaT                   NaT
33  42.260000 -71.898000  ...                NaT                   NaT
34  42.627000 -71.353500  ...         1997-01-01            2002-12-31
36  41.702400 -70.781000  ...                NaT                   NaT
37  42.112000 -70.708000  ...                NaT                   NaT
38  42.388000 -72.067000  ...         1995-01-01            2017-12-05
39  41.925700 -70.831470  ...                NaT                   NaT
40  41.279000 -70.165000  ...                NaT                   NaT
41  41.662589 -70.957314  ...                NaT                   NaT
42  42.293850 -72.716220  ...         2008-03-13            2017-06-30
43  41.664700 -70.547900  ...                NaT                   NaT
44  42.202500 -72.322000  ...                NaT                   NaT
45  42.039200 -71.292000  ...         2003-03-01                   NaT
47  42.241700 -71.045030  ...         2009-03-30            2009-12-31
50  42.180600 -71.078400  ...         2000-02-01            2010-06-01
51  42.405000 -71.542000  ...                NaT                   NaT
52  42.581400 -71.245000  ...                NaT                   NaT
53  42.220000 -72.558000  ...                NaT                   NaT
54  42.411500 -71.712800  ...                NaT                   NaT
55  42.106910 -72.032400  ...         2012-01-03                   NaT
56  42.043815 -72.118011  ...                NaT                   NaT
57  41.922300 -71.083600  ...         1997-09-01                   NaT
59  42.363267 -71.380817  ...                NaT                   NaT
60  42.581000 -72.045000  ...         2010-03-01                   NaT
61  42.148000 -72.748000  ...         2004-06-11            2006-06-30
62  42.678800 -72.060200  ...                NaT                   NaT

    Project Type Category  LFG Energy Project Type RNG Delivery Method  \
0                 Unknown                  Unknown                 NaN
1                 Unknown                  Unknown                 NaN
2             Electricity     Reciprocating Engine                 NaN
5                 Unknown                  Unknown                 NaN
6             Electricity            Steam Turbine                 NaN
7                 Unknown                  Unknown                 NaN
8             Electricity                Fuel Cell                 NaN
9                 Unknown                  Unknown                 NaN
10                Unknown                  Unknown                 NaN
11            Electricity     Reciprocating Engine                 NaN
12            Electricity     Reciprocating Engine                 NaN
13            Electricity     Reciprocating Engine                 NaN
14                Unknown                  Unknown                 NaN
15                Unknown                  Unknown                 NaN
16            Electricity     Reciprocating Engine                 NaN
18            Electricity              Gas Turbine                 NaN
21            Electricity     Reciprocating Engine                 NaN
25                Unknown                  Unknown                 NaN
26                Unknown                  Unknown                 NaN
27            Electricity     Reciprocating Engine                 NaN
28                Unknown                  Unknown                 NaN
29            Electricity     Reciprocating Engine                 NaN
30                Unknown                  Unknown                 NaN
31            Electricity     Reciprocating Engine                 NaN
32                Unknown                  Unknown                 NaN
33                Unknown                  Unknown                 NaN
34            Electricity     Reciprocating Engine                 NaN
36                Unknown                  Unknown                 NaN
37                Unknown                  Unknown                 NaN
38            Electricity     Reciprocating Engine                 NaN
39                Unknown                  Unknown                 NaN
40                Unknown                  Unknown                 NaN
41                Unknown                  Unknown                 NaN
42            Electricity     Reciprocating Engine                 NaN
43                Unknown                  Unknown                 NaN
44                Unknown                  Unknown                 NaN
45            Electricity     Reciprocating Engine                 NaN
47            Electricity     Reciprocating Engine                 NaN
50            Electricity     Reciprocating Engine                 NaN
51                Unknown                  Unknown                 NaN
52                Unknown                  Unknown                 NaN
53                Unknown                  Unknown                 NaN
54                Unknown                  Unknown                 NaN
55            Electricity     Reciprocating Engine                 NaN
56                Unknown                  Unknown                 NaN
57            Electricity     Reciprocating Engine                 NaN
59                Unknown                  Unknown                 NaN
60            Electricity     Reciprocating Engine                 NaN
61            Electricity     Reciprocating Engine                 NaN
62                Unknown                  Unknown                 NaN

    Actual MW Generation  Rated MW Capacity LFG Flow to Project (mmscfd)  \
0                    NaN                NaN                          NaN
1                    NaN                NaN                          NaN
2                  1.000              1.500                        0.720
5                    NaN                NaN                          NaN
6                    NaN                NaN                          NaN
7                    NaN                NaN                          NaN
8                  0.200                NaN                          NaN
9                    NaN                NaN                          NaN
10                   NaN                NaN                          NaN
11                 2.000                NaN                        1.000
12                 2.450              5.700                        1.218
13                 2.500              3.300                        1.600
14                   NaN                NaN                          NaN
15                   NaN                NaN                          NaN
16                 3.000                NaN                          NaN
18                 3.390              5.244                        2.680
21                 2.800              3.200                        1.440
25                   NaN                NaN                          NaN
26                   NaN                NaN                          NaN
27                 0.420              3.200                        0.420
28                   NaN                NaN                          NaN
29                 2.000                NaN                        1.200
30                   NaN                NaN                          NaN
31                 1.600              1.600                          NaN
32                   NaN                NaN                          NaN
33                   NaN                NaN                          NaN
34                 1.600              1.600                        0.400
36                   NaN                NaN                          NaN
37                   NaN                NaN                          NaN
38                 0.800              0.800                          NaN
39                   NaN                NaN                          NaN
40                   NaN                NaN                          NaN
41                   NaN                NaN                          NaN
42                 0.800              0.800                        0.504
43                   NaN                NaN                          NaN
44                   NaN                NaN                          NaN
45                 0.920              5.600                        0.528
47                 0.421                NaN                          NaN
50                 2.700                NaN                          NaN
51                   NaN                NaN                          NaN
52                   NaN                NaN                          NaN
53                   NaN                NaN                          NaN
54                   NaN                NaN                          NaN
55                 1.410              1.600                        0.705
56                   NaN                NaN                          NaN
57                 0.700              1.900                        0.400
59                   NaN                NaN                          NaN
60                 0.500              1.620                          NaN
61                 0.240                NaN                          NaN
62                   NaN                NaN                          NaN

    Current Year Emission Reductions (MMTCO2e/yr) - Direct  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                            0.12397
13                                            0.12650
14                                                NaN
15                                                NaN
16                                                NaN
18                                            0.17154
21                                            0.14168
25                                                NaN
26                                                NaN
27                                            0.02125
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN

In [7]:
selected_columns.to_csv('landfill.csv')